name: Deploy Monitoring
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Ansible Lint
        uses: ansible/ansible-lint@v6
        with:
          path: "ansible/"
